output:
  - platform: gpio
    pin: GPIO5
    id: relay

switch:
  - platform: output
    name: light
    output: relay
    id: deviceid
    restore_mode: RESTORE_DEFAULT_OFF
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    name: switch_1
    id: switchid1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    pin:
      number: GPIO14
    name: switch_2
    id: switchid2

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: deviceid
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin: GPIO0